### PR TITLE
Add preview link to readme

### PR DESCRIPTION
**Pull request by rtgibbons**
Links for Atlasssian them and Default Jenkins.

### CODE REVIEW

**Comment by djonsson** [comment]
The preview seems to be offline at the moment. I noticed that it was offline earlier as well. Is there a problem with hosting Jenkins on heroku?

**Comment by rtgibbons** [comment]
That's why i added the Note below the link. Since it's on a single Dyno, Heroku puts them to sleep after a period of no requests. There are some "hack" to keep them from going to sleep (by setting a cron job to request a page of itself, which ironically we might be able to do with a Jenkins job.

But if you give a minute to load it will come all the way up back up.

**Comment by djonsson** [comment]
Cool, let's create a job that keeps the demo app alive with the following settings:

**Build Triggers  - Build Periodically**
`*/5 * * * *`

**And this to be executed in the job (I guess fetching only headers will do the trick)**
`curl -I https://jenkins-atlassian-theme.herokuapp.com/ `

**Comment by rtgibbons** [comment]
I've got that added in for the theme right now. If it works, i'll merge it to the others. I'll try to remember to check it in 24 - 48 hours.

**Comment by djonsson** [comment]
We are getting a new error now on the app. I guess we are hitting a traffic limit or something?

**Comment by rtgibbons** [comment]
Hmm, it's working for me. What did it say? Can you grab a screenshot next time?

**Comment by rtgibbons** [comment]
BTW I found it was exceeding their quota of free app running time

> desc="Free app running time quota exhausted"

I've removed the cron job to refresh for now, I'll research it more later and see what i can find.

**Pull request merged**
