### PR TITLE
Added `dist` into repository

### PR DESCRIPTION
**Pull request by o5**
Hello, 

I've Jenkins on HTTPS and I need hosted CSS/JS on HTTPS too. So, I've included generated `dist` folder and now, I can use http://rawgit.com/.

There is "my" CDN:

https://cdn.rawgit.com/o5/jenkins-atlassian-theme/master/dist/theme.css
https://cdn.rawgit.com/o5/jenkins-atlassian-theme/master/dist/theme.js 

Your https://master.source.test.do/dist/theme.css doesn't have SSL certificate.

### CODE REVIEW

**Comment by jacksoncage** [comment]
Url with included SSL certificate is active but docs are not merged into master yet @o5. Here's the current dock from develop branch:

```
Master (Stable)

Hosted CSS: https://test.do/master/dist/theme.css
Hosted Javascript: https://test.do/master/dist/theme.js
Develop (Test environment)

Hosted CSS: https://test.do/develop/dist/theme.css
Hosted Javascript: https://test.do/develop/dist/theme.js
```
see https://github.com/djonsson/jenkins-atlassian-theme/tree/develop#hosted-installation

**Comment by jacksoncage** [comment]
@djonsson should we merge in develop into master?

**Comment by o5** [comment]
So stupid, sorry :)

**Comment by jacksoncage** [comment]
Not at all @o5, we should have merged on develop a while a go, so thanks for the PR and comments!

**Pull request closed without merging**
